### ISSUE TITLE
web server not responding

### ISSUE THREAD

**Issue by tars01** [mtnbikeray/Incidence-Deflection-Gauge#1]
Hi, nice little project. 

I have an issue which maybe you have seen. I configure the AP (connect to my SSID) Configure it with a static IP and reboot it. I know this works because If I leave a ping running I can see it start responding. The problem is when I try web to it there is no response. Actually, it seems to listen on port 80 because if I telnet to it on port 80 it seems to accept that connection.

In your instructions you mention the blue light should turn off when it boots. Mine stays on.

Thanks

**Comment by mtnbikeray** [comment]
Each time the device is powered on it needs to calibrate the sensors. During this time the blue led will be on solid. Place the two sensors on a flat surface before powering on and don’t move them until the led starts flashing rapidly. This calibration process takes about two minutes.Once the calibration process finishes and the LED is flashing rapidly, the device is ready to display data. It will not respond until the calibration completes.BTW  I’ve never used the fixed ip option. RayOn May 29, 2024, at 4:04 AM, M ***@***.***> wrote:﻿
Hi, nice little project.
I have an issue which maybe you have seen. I configure the AP (connect to my SSID) Configure it with a static IP and reboot it. I know this works because If I leave a ping running I can see it start responding. The problem is when I try web to it there is no response. Actually, it seems to listen on port 80 because if I telnet to it on port 80 it seems to accept that connection.
In your instructions you mention the blue light should turn off when it boots. Mine stays on.
Thanks

**Comment by mtnbikeray** [comment]
﻿Also, if a sensor isn’t responding this can happen since it can’t complete the calibration. Double check wiring.  Could be bad sensor alsoSCL to D1SDA to D2RayOn May 29, 2024, at 4:04 AM, M ***@***.***> wrote:﻿
Hi, nice little project.
I have an issue which maybe you have seen. I configure the AP (connect to my SSID) Configure it with a static IP and reboot it. I know this works because If I leave a ping running I can see it start responding. The problem is when I try web to it there is no response. Actually, it seems to listen on port 80 because if I telnet to it on port 80 it seems to accept that connection.
In your instructions you mention the blue light should turn off when it boots. Mine stays on.
Thanks

**Comment by tars01** [comment]
OK thanks.. I've left it for over half an hour and still nothing. I will try with the DHCP option and see if I have any luck. Also tried re-flashing it etc. 

Cheers

**Comment by mtnbikeray** [comment]
You can get some debug out of it by connecting to the usb/ serial port using  something like PuTTY. That will identify the problem Baud rate is 115200RayOn May 29, 2024, at 9:29 AM, M ***@***.***> wrote:﻿
OK thanks.. I've left it for over half an hour and still nothing. I will try with the DHCP option and see if I have any luck. Also tried re-flashing it etc.
Cheers

**Comment by mtnbikeray** [comment]
﻿Also, if a sensor isn’t responding this can happen since it can’t complete the calibration. Double check wiring.  Could be bad sensor alsoSCL to D1SDA to D2You can get some debug out of it by connecting to the usb/ serial port using  something like PuTTY. That will identify the problem Baud rate is 115200RayOn May 29, 2024, at 9:29 AM, M ***@***.***> wrote:﻿
OK thanks.. I've left it for over half an hour and still nothing. I will try with the DHCP option and see if I have any luck. Also tried re-flashing it etc.
Cheers

**Comment by tars01** [comment]
Thanks for the tip. I connected with putty via serial like you said but it just shows dots incrementing.. . . . . . . .  So I think it's waiting for the sensor like you say. 

I followed the wiring schematics but one of your two schematics shows 5V doing to VCC as well as ACO. So the first sensor I wired as shown in "wemos_schematic.jpeg" and the sensor I wired as per "sensor2_schematic.jpeg" So what I did was splice the red cable with an extra bit so it's a Y shape, and I had 5V go to VCC and ACO. That was the only part I wasn't 100% sure about but that seemed how it should be.

Cheers

**Comment by mtnbikeray** [comment]
Your wiring is good as long as only one sensor has 5v going to ad0 (that is
sensor 2)

Look at the debug after the ip address you’ll get some dots. If you never
see
an x y z value it’s sensor one not initializing. If you do see dots
followed by x y z followed by the more dots that never end it’s sensor two

If it’s sensor one giving you trouble try removing the ad0 jumper on sensor
two and only connect that one sensor and look at debug and tell me what you
see.

Ray
